from django.urls import path
from app_shop.views import (
    SignUpView,
    LoginView,
    RestorePasswordView,
    LogoutUserView,
    CategoryDetailView,
    SubcategoryDetailView,
    TagDetailView,
    SearchGoodListView,
    add_cart,
    add_review,
    payment,
    payment_someone,
    about,
    AccountView,
    CartView,
    CatalogListView,
    HistoryOrderView,
    IndexView,
    OneOrderDetailView,
    OrderView,
    ProductDetailView,
    ProfileView,
    progress_payment,
    sale
)


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search/', SearchGoodListView.as_view(), name='search'),
    path('add_cart/', add_cart, name='add_cart'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('category/<int:category>/<int:pk>/', SubcategoryDetailView.as_view(), name='subcategory_detail'),
    path('tag/<int:pk>/', TagDetailView.as_view(), name='tag_detail'),
    path('about/', about, name='about'),
    path('account/', AccountView.as_view(), name='account'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/reduce#<int:good>&<int:cart>/', CartView.reduce_quantity, name='reduce_quantity'),
    path('cart/increase#<int:good>&<int:cart>/', CartView.increase_quantity, name='increase_quantity'),
    path('cart/change_quantity/', CartView.change_quantity, name='change_quantity'),
    path('cart/remove#<int:good>&<int:cart>/', CartView.remove_from_cart, name='remove_from_cart'),
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('oneorder/<int:pk>/', OneOrderDetailView.as_view(), name='one_order'),
    path('historyorder/', HistoryOrderView.as_view(), name='history_order'),
    path('order/', OrderView.as_view(), name='order'),
    path('order/order_confirm/', OrderView.order_confirm, name='order_confirm'),
    path('order/order_creation/', OrderView.order_creation, name='order_creation'),
    path('payment/<int:pk>/', payment, name='payment'),
    path('paymentsomeone/<int:pk>/', payment_someone, name='payment_someone'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product'),
    path('product/<int:pk>/add_review/', add_review, name='add_review'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('restore_password/', RestorePasswordView.as_view(), name='restore_password'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('progresspayment/', progress_payment, name='progress_payment'),
    path('sale/', sale, name='sale'),
]
