# Generated by Django 4.1.5 on 2023-01-09 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['good'], 'verbose_name': 'отзыв на товар', 'verbose_name_plural': 'отзывы на товар'},
        ),
        migrations.AddField(
            model_name='review',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата отзыва'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
