# Generated by Django 4.1.5 on 2023-01-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_alter_review_options_review_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['current_price'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
