# Generated by Django 4.1.5 on 2023-01-11 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_alter_good_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodincart',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество'),
        ),
    ]
