# Generated by Django 4.1.5 on 2023-01-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_alter_deliverytype_free_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='free_delivery',
            field=models.BooleanField(blank=True, choices=[(True, 'Доступна'), (False, 'Недоступна')], default=False, null=True, verbose_name='возможность бесплатной доставки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата отзыва'),
        ),
    ]
