# Generated by Django 4.1.5 on 2023-01-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_alter_deliverytype_free_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='фото пользователя'),
        ),
    ]
