# Generated by Django 4.1.5 on 2023-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_review_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_error',
            field=models.CharField(default=1, max_length=50, verbose_name='ошибка при оплате'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_error_message',
            field=models.CharField(default=1, max_length=200, verbose_name='сообщение об ошибке при оплате'),
            preserve_default=False,
        ),
    ]
