# Generated by Django 4.1.5 on 2023-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0008_order_payment_error_order_payment_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_error',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ошибка при оплате'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_error_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='сообщение об ошибке при оплате'),
        ),
    ]
