# Generated by Django 4.1.5 on 2023-01-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0009_alter_order_payment_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodinorder',
            name='price',
            field=models.FloatField(default=1, verbose_name='цена товара'),
            preserve_default=False,
        ),
    ]
