# Generated by Django 4.1.5 on 2023-01-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0010_goodinorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_reviews', to='app_shop.good', verbose_name='товар'),
        ),
    ]
