# Generated by Django 4.1.5 on 2023-01-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0011_alter_review_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='number_of_requests',
            field=models.IntegerField(blank=True, default=0, null=0, verbose_name='количество запросов по тегу'),
        ),
    ]
