# Generated by Django 4.1.5 on 2023-01-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0012_tag_number_of_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='number_of_requests',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество запросов по тегу'),
        ),
    ]
