# Generated by Django 4.1.5 on 2023-01-16 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0013_alter_tag_number_of_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='current_price',
            field=models.FloatField(blank=True, null=True, verbose_name='текущая цена'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='размер скидки'),
        ),
    ]
